[project]
name = "patch-denoising"
version = "1.0"
description = "Denoising method for sequence of images or volumes. Primarly targeting fMRI data."
authors = [{name="Pierre-antoine Comby", email="pierre-antoine.comby@crans.org"}]

dependencies = ["numpy", "scipy", "matplotlib", "tqdm"]

[project.optional-dependencies]
test = ["pytest", "pytest-cov", "pytest-xdist", "pytest-sugar"]
doc = ["pydata-sphinx-theme", "numpydoc", "sphinx_gallery", "sphinx"]
dev = ["black", "isort"]

[build-system]
requires = ["setuptools", "wheel"]


[tool.coverage.run]
omit = ["*tests*", "denoiser/bindings/*"]

[tool.coverage.report]
precision = 2
exclude_lines = ["pragma: no cover", "raise NotImplementedError"]

[tool.flake8]
docstring-convention = "numpy"
ignore = ["D105"]

# Formatting using black.
[tool.black]

[tool.isort]
profile="black"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = [
    "--cov=denoiser",
    "--cov-report=term-missing",
]
